# Generated by Django 4.0.1 on 2022-01-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_bio_profile_completedchall'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='tries',
            field=models.IntegerField(default=0),
        ),
    ]
