# Generated by Django 4.0.1 on 2022-01-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_challenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='challenges',
            field=models.JSONField(default=list),
        ),
    ]
