# Generated by Django 4.0.1 on 2022-01-31 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tries',
        ),
    ]
