# Generated by Django 4.0.1 on 2022-02-21 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satom', '0004_remove_challenge_completed'),
        ('users', '0008_rename_currentking_roi_king_roi_challenge_roi_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roi',
            name='challenge',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='satom.challenge'),
        ),
    ]
