# Generated by Django 4.0.1 on 2022-02-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_roi_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roi',
            name='challenge',
        ),
        migrations.AddField(
            model_name='roi',
            name='challengeID',
            field=models.IntegerField(default=1),
        ),
    ]
