# Generated by Django 4.0.1 on 2022-01-25 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('satom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='completed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
