# Generated by Django 4.0.1 on 2022-01-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('satom', '0002_challenge_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='completed',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
