# Generated by Django 6.0 on 2025-12-12 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satom', '0005_challenge_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='word',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
