# Generated by Django 6.0 on 2025-12-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satom', '0006_challenge_date_alter_challenge_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotPossible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=20, unique=True)),
                ('difficulte', models.IntegerField(default=1)),
                ('longueur', models.IntegerField(default=0)),
            ],
        ),
    ]
