# Generated by Django 6.0 on 2025-12-12 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satom', '0007_motpossible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
