# Generated by Django 6.0 on 2025-12-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satom', '0008_alter_challenge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='motpossible',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='motpossible',
            name='longueur',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
