# Generated by Django 6.0 on 2026-01-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enclose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enclosescore',
            name='walls',
            field=models.JSONField(default='test'),
            preserve_default=False,
        ),
    ]
