# Generated by Django 6.0 on 2026-01-03 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enclose', '0002_enclosescore_walls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnclosePuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_id', models.CharField(max_length=32, unique=True)),
                ('date', models.DateField(unique=True)),
                ('size', models.PositiveIntegerField()),
                ('max_walls', models.PositiveIntegerField()),
                ('grid', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.PositiveIntegerField()),
                ('walls', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='enclose.enclosepuzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enclose_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-area', 'created_at'],
                'unique_together': {('user', 'puzzle')},
            },
        ),
        migrations.DeleteModel(
            name='EncloseScore',
        ),
    ]
