# Generated by Django 6.0 on 2026-01-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enclose', '0003_enclosepuzzle_puzzlescore_delete_enclosescore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puzzlescore',
            options={'ordering': ['-area', 'walls_used', 'created_at']},
        ),
        migrations.AddField(
            model_name='puzzlescore',
            name='walls_used',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
